# builder stage
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./

# Install dependencies
RUN npm ci 
COPY . .
# produce dist/
RUN npm run build      


# production stage
FROM node:18-alpine AS production
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/src/main.js"]

