version: "3.9"

services:
  message_broker:
    image: nats:latest
    container_name: drone_fleet_message_broker
    ports:
      - "4222:4222"  # Client
      - "6222:6222"  # Cluster routes
      - "8222:8222"  # Monitoring
    volumes:
      - ./nats_data:/data
    command: -js -m 8222 -store_dir /data

  websocket:
    build:
      context: ../websocket
      dockerfile: Dockerfile.dev
    container_name: drone_fleet_websocket
    network_mode: "host"
    volumes:
      - ../websocket:/app
      - ../broker-sdk:/broker-sdk
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    depends_on:
      - message_broker
      
  drone1:
    image: ardupilot
    container_name: drone1
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - ../ardupilot:/ardupilot
    command: /ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -f quad --sysid 1 --out=udp:127.0.0.1:14555

  orchestrator:
    build:
      context: ../orchestrator
      dockerfile: Dockerfile.dev
    container_name: drone_fleet_orchestrator
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ../orchestrator:/app
      - ../broker-sdk:/broker-sdk
      - /app/node_modules
    # ports:
    #   - "14550:14550/udp"   # ← MAVLink UDP port can ignore if using network "host"
    environment:
      NODE_ENV: production
    command: npm run dev
    depends_on:
      - message_broker

