server {
    listen 80;
    server_name admin.dronefleet;

    location / {
        proxy_pass http://drone_fleet_admin:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name api.dronefleet;

    location / {
        proxy_pass http://drone_fleet_api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name pgadmin.dronefleet;

    location / {
        proxy_pass http://drone_fleet_pgadmin:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}